# change

on: 
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with: 
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: ./vendor/bin/phpunit tests


