name: Test Application

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

